package com.note.entity.fiction.entity;

import java.util.Date;

public class FictionChapterEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.chapter_sort
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String chapterSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.chapter_type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer chapterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.chapter_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer chapterViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.chapter_word_count
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer chapterWordCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.cid
     *
     * @return the value of fiction_chapter.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.cid
     *
     * @param cid the value for fiction_chapter.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.logic_code
     *
     * @return the value of fiction_chapter.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.logic_code
     *
     * @param logicCode the value for fiction_chapter.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.fiction_code
     *
     * @return the value of fiction_chapter.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getFictionCode() {
        return fictionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.fiction_code
     *
     * @param fictionCode the value for fiction_chapter.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionCode(String fictionCode) {
        this.fictionCode = fictionCode == null ? null : fictionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.chapter_sort
     *
     * @return the value of fiction_chapter.chapter_sort
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getChapterSort() {
        return chapterSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.chapter_sort
     *
     * @param chapterSort the value for fiction_chapter.chapter_sort
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterSort(String chapterSort) {
        this.chapterSort = chapterSort == null ? null : chapterSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.chapter_name
     *
     * @return the value of fiction_chapter.chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.chapter_name
     *
     * @param chapterName the value for fiction_chapter.chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.chapter_type
     *
     * @return the value of fiction_chapter.chapter_type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getChapterType() {
        return chapterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.chapter_type
     *
     * @param chapterType the value for fiction_chapter.chapter_type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterType(Integer chapterType) {
        this.chapterType = chapterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.chapter_views
     *
     * @return the value of fiction_chapter.chapter_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getChapterViews() {
        return chapterViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.chapter_views
     *
     * @param chapterViews the value for fiction_chapter.chapter_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterViews(Integer chapterViews) {
        this.chapterViews = chapterViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.chapter_word_count
     *
     * @return the value of fiction_chapter.chapter_word_count
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getChapterWordCount() {
        return chapterWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.chapter_word_count
     *
     * @param chapterWordCount the value for fiction_chapter.chapter_word_count
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterWordCount(Integer chapterWordCount) {
        this.chapterWordCount = chapterWordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.create_time
     *
     * @return the value of fiction_chapter.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.create_time
     *
     * @param createTime the value for fiction_chapter.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.modify_time
     *
     * @return the value of fiction_chapter.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.modify_time
     *
     * @param modifyTime the value for fiction_chapter.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.create_user_id
     *
     * @return the value of fiction_chapter.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.create_user_id
     *
     * @param createUserId the value for fiction_chapter.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.modify_user_id
     *
     * @return the value of fiction_chapter.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.modify_user_id
     *
     * @param modifyUserId the value for fiction_chapter.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter.is_delete
     *
     * @return the value of fiction_chapter.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter.is_delete
     *
     * @param isDelete the value for fiction_chapter.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}