package com.note.entity.fiction.entity;

import java.util.Date;

public class FictionRankEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_score
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Double fictionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer fictionViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.cid
     *
     * @return the value of fiction_rank.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.cid
     *
     * @param cid the value for fiction_rank.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.logic_code
     *
     * @return the value of fiction_rank.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.logic_code
     *
     * @param logicCode the value for fiction_rank.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.fiction_code
     *
     * @return the value of fiction_rank.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getFictionCode() {
        return fictionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.fiction_code
     *
     * @param fictionCode the value for fiction_rank.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionCode(String fictionCode) {
        this.fictionCode = fictionCode == null ? null : fictionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.fiction_name
     *
     * @return the value of fiction_rank.fiction_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getFictionName() {
        return fictionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.fiction_name
     *
     * @param fictionName the value for fiction_rank.fiction_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionName(String fictionName) {
        this.fictionName = fictionName == null ? null : fictionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.fiction_score
     *
     * @return the value of fiction_rank.fiction_score
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Double getFictionScore() {
        return fictionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.fiction_score
     *
     * @param fictionScore the value for fiction_rank.fiction_score
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionScore(Double fictionScore) {
        this.fictionScore = fictionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.fiction_views
     *
     * @return the value of fiction_rank.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getFictionViews() {
        return fictionViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.fiction_views
     *
     * @param fictionViews the value for fiction_rank.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionViews(Integer fictionViews) {
        this.fictionViews = fictionViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.is_delete
     *
     * @return the value of fiction_rank.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.is_delete
     *
     * @param isDelete the value for fiction_rank.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.create_time
     *
     * @return the value of fiction_rank.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.create_time
     *
     * @param createTime the value for fiction_rank.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.modify_time
     *
     * @return the value of fiction_rank.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.modify_time
     *
     * @param modifyTime the value for fiction_rank.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.create_user_id
     *
     * @return the value of fiction_rank.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.create_user_id
     *
     * @param createUserId the value for fiction_rank.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_rank.modify_user_id
     *
     * @return the value of fiction_rank.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_rank.modify_user_id
     *
     * @param modifyUserId the value for fiction_rank.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }
}