package com.note.entity.fiction.entity;

import java.util.Date;

public class FictionExtentionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionCode;

    private Double fictionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.full_desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fullDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.total_chapter
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer totalChapter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.last_update_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer fictionViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.last_chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String lastChapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.last_chapter_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String lastChapterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.cid
     *
     * @return the value of fiction_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.cid
     *
     * @param cid the value for fiction_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.logic_code
     *
     * @return the value of fiction_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.logic_code
     *
     * @param logicCode the value for fiction_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.fiction_code
     *
     * @return the value of fiction_extention.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getFictionCode() {
        return fictionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.fiction_code
     *
     * @param fictionCode the value for fiction_extention.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionCode(String fictionCode) {
        this.fictionCode = fictionCode == null ? null : fictionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.full_desc
     *
     * @return the value of fiction_extention.full_desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getFullDesc() {
        return fullDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.full_desc
     *
     * @param fullDesc the value for fiction_extention.full_desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFullDesc(String fullDesc) {
        this.fullDesc = fullDesc == null ? null : fullDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.total_chapter
     *
     * @return the value of fiction_extention.total_chapter
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getTotalChapter() {
        return totalChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.total_chapter
     *
     * @param totalChapter the value for fiction_extention.total_chapter
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setTotalChapter(Integer totalChapter) {
        this.totalChapter = totalChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.last_update_time
     *
     * @return the value of fiction_extention.last_update_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.last_update_time
     *
     * @param lastUpdateTime the value for fiction_extention.last_update_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.level
     *
     * @return the value of fiction_extention.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.level
     *
     * @param level the value for fiction_extention.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.fiction_views
     *
     * @return the value of fiction_extention.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getFictionViews() {
        return fictionViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.fiction_views
     *
     * @param fictionViews the value for fiction_extention.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setFictionViews(Integer fictionViews) {
        this.fictionViews = fictionViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.last_chapter_name
     *
     * @return the value of fiction_extention.last_chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLastChapterName() {
        return lastChapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.last_chapter_name
     *
     * @param lastChapterName the value for fiction_extention.last_chapter_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLastChapterName(String lastChapterName) {
        this.lastChapterName = lastChapterName == null ? null : lastChapterName.trim();
    }

    public String getLastChapterCode() {
        return lastChapterCode;
    }

    public void setLastChapterCode(String lastChapterCode) {
        this.lastChapterCode = lastChapterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.create_time
     *
     * @return the value of fiction_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.create_time
     *
     * @param createTime the value for fiction_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.modify_time
     *
     * @return the value of fiction_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.modify_time
     *
     * @param modifyTime the value for fiction_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.create_user_id
     *
     * @return the value of fiction_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.create_user_id
     *
     * @param createUserId the value for fiction_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.modify_user_id
     *
     * @return the value of fiction_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.modify_user_id
     *
     * @param modifyUserId the value for fiction_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_extention.is_delete
     *
     * @return the value of fiction_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_extention.is_delete
     *
     * @param isDelete the value for fiction_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Double getFictionScore() {
        return fictionScore;
    }

    public void setFictionScore(Double fictionScore) {
        this.fictionScore = fictionScore;
    }
}