package com.note.entity.fiction.entity;

import java.util.Date;

public class FictionChapterExtentionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.chapter_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String chapterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_chapter_extention.chapter_content
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private byte[] chapterContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.cid
     *
     * @return the value of fiction_chapter_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.cid
     *
     * @param cid the value for fiction_chapter_extention.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.logic_code
     *
     * @return the value of fiction_chapter_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.logic_code
     *
     * @param logicCode the value for fiction_chapter_extention.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.chapter_code
     *
     * @return the value of fiction_chapter_extention.chapter_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getChapterCode() {
        return chapterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.chapter_code
     *
     * @param chapterCode the value for fiction_chapter_extention.chapter_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterCode(String chapterCode) {
        this.chapterCode = chapterCode == null ? null : chapterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.create_time
     *
     * @return the value of fiction_chapter_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.create_time
     *
     * @param createTime the value for fiction_chapter_extention.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.create_user_id
     *
     * @return the value of fiction_chapter_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.create_user_id
     *
     * @param createUserId the value for fiction_chapter_extention.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.modify_time
     *
     * @return the value of fiction_chapter_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.modify_time
     *
     * @param modifyTime the value for fiction_chapter_extention.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.modify_user_id
     *
     * @return the value of fiction_chapter_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.modify_user_id
     *
     * @param modifyUserId the value for fiction_chapter_extention.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.is_delete
     *
     * @return the value of fiction_chapter_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.is_delete
     *
     * @param isDelete the value for fiction_chapter_extention.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fiction_chapter_extention.chapter_content
     *
     * @return the value of fiction_chapter_extention.chapter_content
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public byte[] getChapterContent() {
        return chapterContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fiction_chapter_extention.chapter_content
     *
     * @param chapterContent the value for fiction_chapter_extention.chapter_content
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setChapterContent(byte[] chapterContent) {
        this.chapterContent = chapterContent;
    }
}