package com.note.entity.fiction.entity;

import java.util.Date;

public class SystemUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.phone
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.photo
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_password
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.email
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.address
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.cid
     *
     * @return the value of system_user.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.cid
     *
     * @param cid the value for system_user.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.logic_code
     *
     * @return the value of system_user.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.logic_code
     *
     * @param logicCode the value for system_user.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.name
     *
     * @return the value of system_user.name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.name
     *
     * @param name the value for system_user.name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.phone
     *
     * @return the value of system_user.phone
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.phone
     *
     * @param phone the value for system_user.phone
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.photo
     *
     * @return the value of system_user.photo
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.photo
     *
     * @param photo the value for system_user.photo
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.type
     *
     * @return the value of system_user.type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.type
     *
     * @param type the value for system_user.type
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.level
     *
     * @return the value of system_user.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.level
     *
     * @param level the value for system_user.level
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_name
     *
     * @return the value of system_user.login_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_name
     *
     * @param loginName the value for system_user.login_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_password
     *
     * @return the value of system_user.login_password
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_password
     *
     * @param loginPassword the value for system_user.login_password
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.email
     *
     * @return the value of system_user.email
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.email
     *
     * @param email the value for system_user.email
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.address
     *
     * @return the value of system_user.address
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.address
     *
     * @param address the value for system_user.address
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.create_time
     *
     * @return the value of system_user.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.create_time
     *
     * @param createTime the value for system_user.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.modify_time
     *
     * @return the value of system_user.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.modify_time
     *
     * @param modifyTime the value for system_user.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.create_user_id
     *
     * @return the value of system_user.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.create_user_id
     *
     * @param createUserId the value for system_user.create_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.modify_user_id
     *
     * @return the value of system_user.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.modify_user_id
     *
     * @param modifyUserId the value for system_user.modify_user_id
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.is_delete
     *
     * @return the value of system_user.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.is_delete
     *
     * @param isDelete the value for system_user.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}